send_text:
  name: "Отправить текст"
  description: "Выводит текстовое сообщение на экран TimesFrame"
  fields:
    message:
      name: "Сообщение"
      description: "Текст, который будет отображен"
      required: true
      example: "Привет!"
      selector:
        text:
    color:
      name: "Цвет"
      description: "Цвет текста в формате HEX"
      default: "#FFFFFF"
      selector:
        color_rgb:
    x:
      name: "Координата X"
      description: "Положение по горизонтали"
      default: 0
      selector:
        number:
          min: 0
          max: 128
          mode: box
    y:
      name: "Координата Y"
      description: "Положение по вертикали"
      default: 16
      selector:
        number:
          min: 0
          max: 64
          mode: box
